### PR TITLE
Add barcode tag to mark dups helper

### PR DESCRIPTION
**Pull request by ebelter**

### CODE REVIEW

**Comment by ebelter** [comment]
@jasonwalker80 Can you take a look? For genome/docker-dna-alignment#5

**Comment by ebelter** [comment]
Do we have a small bam we could setup to run bats tests on? Or is that overkill?

**Comment by jasonwalker80** [comment]
I'd suggest making one from the unaligned BAM files we have for CYP2D6 targeted testing. The samples are 1kg samples, specifically the Genome-in-a-Bottle sample NA12878 is one of them:
```
/gscmnt/gc2568/techd/CIS-92/unaligned/2897467231-H_IJ-NA12878-NA12878_K10-ATTACTCG.bam
```
You could downsample/subset that and use it in automated tests and include in the git repo as test data.

**Review by jasonwalker80 — APPROVED** [review]
+2

**Comment by ebelter** [comment]
@jasonwalker80 I am not an admin on this repo. Can you merge this PR?

**Comment by jasonwalker80** [comment]
I added you to the 'Docker Tools' mgibio team. You should have Admin access now.

**Pull request merged**
